### PR TITLE
Add SNPchip as a dependency.

### PR DESCRIPTION
**Pull request by roryk**
Luca brought this up here bcbio/bcbio-nextgen#2874, the dependency is checked for [here](https://github.com/gavinha/TitanCNA/blob/9c45b4eb9e2e3a5cfd1e1be245b767186d6972d3/scripts/R_scripts/titanCNA.R#L29), but isn't included in the DESCRIPTION as a dependency. This adds it.

Thanks!

If this pull request is mangled, forgive me, trying out [hub](https://hub.github.com) for the first time. :)

### CODE REVIEW

**Comment by gavinha** [comment]
Hi @roryk 

Thank you for bringing up this issue and carrying the discussion in https://github.com/bcbio/bcbio-nextgen/issues/2874. 
While `SNPchip` is currently being used to plot the idiogram, it is not actually necessary within the TitanCNA R package itself. It is being used in the `titanCNA.R` script, which is provided as a convenience for the user to run TITAN without having build this script themselves. That is, it is the series of commands from the vignette. 

Thanks,
Gavin

**Comment by roryk** [comment]
Hi Gavinha,

Doesn't that mean it is a dependency? This means that TitanCNA is shipping with a script that doesn't work unless you install SNPchip yourself. Since it isn't added as a dependency, it doesn't get picked up by any of the automated builds that bioconductor or bioconda does, so it is shipping with a broken script. Could you reconsider adding this as a dependency?

**Comment by gavinha** [comment]
Hi @roryk 

Thanks for your comment. I am in the process of moving the snakemake workflow out of the TitanCNA repo. And so the `titanCNA.R` script will also leave with it. Then, I'll be removing the `SNPchip` requirement in the vignette if it's not already removed.

My thinking is this TitanCNA repo should stay as just the R package only while workflows can be separate. I've found that most of the minor tinkering and PRs are usually related to the snakemake worflow and the `titanCNA.R` script.

**Comment by roryk** [comment]
Gotcha-- thanks for the clarification, I definitely understand trying to manage support overhead.

**Pull request closed without merging**
